version: "3.5"
services:
  rosbot:
    # lanza bringup sin cámara
    command: >
      ros2 launch rosbot_xl_bringup bringup.launch.py
        mecanum:=True enable_oak:=False
    restart: on-failure

  # Arrancamos sólo lo imprescindible
  rplidar:
    restart: on-failure

  foxglove-ds:
    # búfer y canales ampliados + ignora tipos desconocidos
    command: >
      foxglove_bridge \
        --send-buffer-bytes 33554432 \
        --max-channels 256 \
        --ignore-unknown-types
    depends_on:
      rosbot:
        condition: service_healthy
      rplidar:
        condition: service_healthy
    restart: on-failure

  # El UI web
  foxglove:
    restart: on-failure
