camera:
  ros__parameters:
    pipeline_type: "RGB"

    # Mantener stream aunque no haya suscriptores:
    i_enable_lazy_publisher: false

    # Fuerza menor carga:
    color:
      i_enable: true
      i_resolution: 720     # en lugar de 1080
      i_fps: 15             # baja a 15 FPS
      publish_raw_images: true

    # Desactiva estéreo/NN por ahora:
    stereo:
      i_enable: false
    rectify:
      i_enable: false
    spatial_nn:
      i_enable: false

    # (Opcional si hay X_LINK_ERROR persistente)
    # i_usb_speed: "usb2"
