depthai_ros2:
  ros__parameters:
    pipeline_type: RGBStereo
    rgb:
      enable: true
      resolution: 1080P
      fps: 30
    stereo_i:
      enableDepth: true
      subpixel: true
      leftRightCheck: true
      extended: true
