scan_filter_chain:
- name: remove_near
  type: laser_filters/LaserScanRangeFilter
  params:
    lower_threshold: 0.22
    upper_threshold: 25.0
    lower_replacement_value: 0.0
    upper_replacement_value: .nan
- name: mask_footprint
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_link
    min_x: -0.20
    max_x:  0.20
    min_y: -0.20
    max_y:  0.20
